/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modul2;

import javax.swing.JOptionPane;


/**
 *
 * @author M. Arwani
 */
public class f_Warung extends javax.swing.JFrame {

    /**
     * Creates new form f_Warung
     */
    public f_Warung() {
        initComponents();
        rdgBayar.add(rdoCash);
        rdgBayar.add(rdoQRIS);
        rdgBayar.add(rdoQRIS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgBayar = new javax.swing.ButtonGroup();
        chkSoto = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        chkSate = new javax.swing.JCheckBox();
        chkTeh = new javax.swing.JCheckBox();
        chkJeruk = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtSoto = new javax.swing.JTextField();
        txtSate = new javax.swing.JTextField();
        txtTeh = new javax.swing.JTextField();
        txtJeruk = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rdoCash = new javax.swing.JRadioButton();
        rdoBCA = new javax.swing.JRadioButton();
        rdoQRIS = new javax.swing.JRadioButton();
        btnHitung = new javax.swing.JButton();
        lblBayar = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnKosong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chkSoto.setMnemonic('S');
        chkSoto.setText("Soto : Rp 15000");
        chkSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSotoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MENU");

        chkSate.setMnemonic('a');
        chkSate.setText("Sate : Rp 17000");
        chkSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSateActionPerformed(evt);
            }
        });

        chkTeh.setMnemonic('T');
        chkTeh.setText("Es Teh : Rp 3000");
        chkTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTehActionPerformed(evt);
            }
        });

        chkJeruk.setMnemonic('E');
        chkJeruk.setText("Es Jeruk : Rp 4000");
        chkJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJerukActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("QUANTITY");

        txtSoto.setEditable(false);
        txtSoto.setText("0");

        txtSate.setEditable(false);
        txtSate.setText("0");

        txtTeh.setEditable(false);
        txtTeh.setText("0");

        txtJeruk.setEditable(false);
        txtJeruk.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("CARA BAYAR");

        rdgBayar.add(rdoCash);
        rdoCash.setSelected(true);
        rdoCash.setText("Mandiri Card");

        rdgBayar.add(rdoBCA);
        rdoBCA.setText("BCA Card");

        rdgBayar.add(rdoQRIS);
        rdoQRIS.setText("QRIS");

        btnHitung.setMnemonic('H');
        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lblBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBayar.setText("Cara Bayar : Uang Cash");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setText("Rp 0,-");

        btnKosong.setMnemonic('K');
        btnKosong.setText("KOSONGKAN");
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoQRIS)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdoCash)
                                        .addGap(77, 77, 77)
                                        .addComponent(lblTotal))
                                    .addComponent(rdoBCA)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBayar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(66, 66, 66)
                                        .addComponent(btnHitung)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKosong, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnHitung, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoCash)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoBCA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoQRIS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBayar)
                .addGap(44, 44, 44)
                .addComponent(btnKosong)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkSate)
                            .addComponent(chkSoto)
                            .addComponent(chkTeh)
                            .addComponent(chkJeruk))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2)))
                .addGap(0, 101, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSoto)
                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSate)
                    .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTeh)
                    .addComponent(txtTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkJeruk)
                    .addComponent(txtJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
        // TODO add your handling code here:
        if(chkSoto.isSelected()) {
            txtSoto.setEditable(true);
            txtSoto.setText("1");
        } else {
            txtSoto.setEditable(false);
            txtSoto.setText("0");           
        }
    }//GEN-LAST:event_chkSotoActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        boolean IData = true;
        
        //cek ada atau tidak:
        //menu dipesan tetapi tidak menuliskan Quantity
        //jika ada, maka var IData menjadi false
        
        if(chkSoto.isSelected() && txtSoto.getText() == " ")
            IData = false;
        if(chkSate.isSelected() && txtSate.getText() == " ")
            IData = false;
        if(chkTeh.isSelected() && txtTeh.getText() == " ")
            IData = false;
        if(chkJeruk.isSelected() && txtJeruk.getText() == " ")
            IData = false;
        
        //jika var IData == false, berarti masih ada kesalahan
        //sehingga perlu dimunculkan pesan kesalahan
        
        if(!IData) {
            JOptionPane.showMessageDialog(this, "Data Dilengkapi dahulu");
        } else {
            //untuk memudahkan, buat var baru untuk menampung data
            int nSoto = Integer.parseInt(txtSoto.getText());
            int nSate = Integer.parseInt(txtSate.getText());
            int nTeh = Integer.parseInt(txtTeh.getText());
            int nJeruk = Integer.parseInt(txtJeruk.getText());
            
            //hitung total
            int nTotal = (15000 * nSoto)+(17000 * nSate)+(3000 * nTeh)+(4000 * nJeruk);
            lblTotal.setText("Rp. " +nTotal);
            
            //bagian ini untuk menampilkan cara Bayar
            if (rdoCash.isSelected()) {
            lblBayar.setText("Cara Bayar : KARTU DEBIT MANDRI");
        } else if (rdoBCA.isSelected()) {
            lblBayar.setText("Cara Bayar : KARTU DEBIT BCA");
        } else if (rdoQRIS.isSelected()) {
            lblBayar.setText("Cara Bayar : SCAN QRIS");
        }
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void chkSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateActionPerformed
        // TODO add your handling code here:
        if(chkSate.isSelected()) {
            txtSate.setEditable(true);
            txtSate.setText("1");
        } else {
            txtSate.setEditable(false);
            txtSate.setText("0");           
        }
    }//GEN-LAST:event_chkSateActionPerformed

    private void chkTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTehActionPerformed
        // TODO add your handling code here:
        if(chkTeh.isSelected()) {
            txtTeh.setEditable(true);
            txtTeh.setText("1");
        } else {
            txtTeh.setEditable(false);
            txtTeh.setText("0");           
        }
    }//GEN-LAST:event_chkTehActionPerformed

    private void chkJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJerukActionPerformed
        // TODO add your handling code here:
        if(chkJeruk.isSelected()) {
            txtJeruk.setEditable(true);
            txtJeruk.setText("1");
        } else {
            txtJeruk.setEditable(false);
            txtJeruk.setText("0");           
        }
    }//GEN-LAST:event_chkJerukActionPerformed

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        // TODO add your handling code here:     
        chkSoto.setSelected(false);
        chkSate.setSelected(false);
        chkTeh.setSelected(false);
        chkJeruk.setSelected(false);
        txtSoto.setText("0");
        txtSate.setText("0");
        txtTeh.setText("0");
        txtJeruk.setText("0");
        txtSoto.setEditable(false);
        txtSate.setEditable(false);
        txtTeh.setEditable(false);
        txtJeruk.setEditable(false);
        rdoCash.setSelected(true);
        lblTotal.setText("Rp. 0");
        lblBayar.setText("Cara Bayar");
    }//GEN-LAST:event_btnKosongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_Warung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKosong;
    private javax.swing.JCheckBox chkJeruk;
    private javax.swing.JCheckBox chkSate;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JCheckBox chkTeh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBayar;
    private javax.swing.JLabel lblTotal;
    private javax.swing.ButtonGroup rdgBayar;
    private javax.swing.JRadioButton rdoBCA;
    private javax.swing.JRadioButton rdoCash;
    private javax.swing.JRadioButton rdoQRIS;
    private javax.swing.JTextField txtJeruk;
    private javax.swing.JTextField txtSate;
    private javax.swing.JTextField txtSoto;
    private javax.swing.JTextField txtTeh;
    // End of variables declaration//GEN-END:variables

}
